import { useState, useRef, useEffect } from 'react';
import { Send, ThumbsUp, ThumbsDown, Menu } from 'lucide-react';

interface Message {
  id: number;
  type: 'user' | 'ai';
  text: string;
  timestamp: string;
  citations?: { fileName: string; page: number }[];
  feedback?: 'up' | 'down' | null;
}

interface ChatDashboardProps {
  onToggleSidebar?: () => void;
}

const mockMessages: Message[] = [
  {
    id: 1,
    type: 'user',
    text: 'What is the company policy on remote work?',
    timestamp: '10:30 AM',
  },
  {
    id: 2,
    type: 'ai',
    text: 'According to our Employee Handbook, employees are eligible for hybrid remote work arrangements with manager approval. Full-time remote work requires VP-level authorization and is evaluated case-by-case based on role requirements.',
    timestamp: '10:30 AM',
    citations: [
      { fileName: 'Employee_Handbook_2025.pdf', page: 12 },
      { fileName: 'Remote_Work_Policy.pdf', page: 3 },
    ],
    feedback: null,
  },
  {
    id: 3,
    type: 'user',
    text: 'How do I reset my network password?',
    timestamp: '10:32 AM',
  },
  {
    id: 4,
    type: 'ai',
    text: 'To reset your network password, visit the IT Self-Service Portal at portal.company.com and click "Reset Password". You\'ll need to verify your identity using your registered mobile number or security questions. The new password must be at least 12 characters with uppercase, lowercase, numbers, and special characters.',
    timestamp: '10:32 AM',
    citations: [
      { fileName: 'IT_Security_Policy.pdf', page: 8 },
    ],
    feedback: 'up',
  },
];

export function ChatDashboard({ onToggleSidebar }: ChatDashboardProps) {
  const [messages, setMessages] = useState<Message[]>(mockMessages);
  const [inputText, setInputText] = useState('');
  const [selectedDepartment, setSelectedDepartment] = useState<'All' | 'HR' | 'IT'>('All');
  const [isStreaming, setIsStreaming] = useState(false);
  const chatWindowRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom when messages change
  useEffect(() => {
    if (chatWindowRef.current) {
      chatWindowRef.current.scrollTop = chatWindowRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSendMessage = () => {
    if (!inputText.trim() || isStreaming) return;

    const userMessage: Message = {
      id: Date.now(),
      type: 'user',
      text: inputText,
      timestamp: new Date().toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' }),
    };

    setMessages([...messages, userMessage]);
    setInputText('');
    setIsStreaming(true);

    // Simulate AI streaming response
    setTimeout(() => {
      const aiMessage: Message = {
        id: Date.now() + 1,
        type: 'ai',
        text: `This is a simulated AI response to: "${inputText}". In a production environment, this would be generated by your RAG system with real-time streaming and vector search through your knowledge base filtered by ${selectedDepartment === 'All' ? 'all departments' : selectedDepartment}.`,
        timestamp: new Date().toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' }),
        citations: [
          { fileName: 'Sample_Document.pdf', page: Math.floor(Math.random() * 50) + 1 },
        ],
        feedback: null,
      };

      setMessages((prev) => [...prev, aiMessage]);
      setIsStreaming(false);
    }, 1500);
  };

  const handleFeedback = (messageId: number, rating: 'up' | 'down') => {
    setMessages(
      messages.map((msg) =>
        msg.id === messageId
          ? { ...msg, feedback: msg.feedback === rating ? null : rating }
          : msg
      )
    );
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  return (
    <div className="h-full flex flex-col bg-gray-50">
      {/* Top App Bar - Fixed Height with Proper Layout */}
      <div className="bg-white border-b border-gray-200 h-16 flex items-center px-4 md:px-6">
        <div className="flex items-center justify-between w-full max-w-7xl mx-auto">
          {/* Left Section: Hamburger + Title */}
          <div className="flex items-center gap-6">
            {/* Hamburger Menu Icon */}
            <button
              onClick={onToggleSidebar}
              className="lg:hidden p-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
              aria-label="Toggle sidebar"
            >
              <Menu className="w-6 h-6" />
            </button>

            {/* Page Title */}
            <h1 className="text-xl text-gray-900">Chat Dashboard</h1>
          </div>

          {/* Right Section: Department Filter */}
          <div className="flex items-center gap-3">
            <label className="text-sm text-gray-700 hidden sm:inline">Department Filter:</label>
            <select
              value={selectedDepartment}
              onChange={(e) => setSelectedDepartment(e.target.value as 'All' | 'HR' | 'IT')}
              className="px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent text-sm"
            >
              <option value="All">All</option>
              <option value="HR">HR</option>
              <option value="IT">IT</option>
            </select>
          </div>
        </div>
      </div>

      {/* Chat Window */}
      <div
        ref={chatWindowRef}
        className="flex-1 overflow-y-auto px-4 md:px-6 py-6"
      >
        <div className="max-w-5xl mx-auto space-y-6">
          {messages.map((message) => (
            <div
              key={message.id}
              className={`flex ${message.type === 'user' ? 'justify-end' : 'justify-start'}`}
            >
              <div className={`max-w-2xl ${message.type === 'user' ? 'w-auto' : 'w-full'}`}>
                {/* Message Bubble */}
                <div
                  className={`rounded-lg px-4 py-3 ${
                    message.type === 'user'
                      ? 'bg-blue-600 text-white'
                      : 'bg-white border border-gray-200 text-gray-900'
                  }`}
                >
                  <p className="text-sm whitespace-pre-wrap">{message.text}</p>
                </div>

                {/* Citations (AI messages only) */}
                {message.type === 'ai' && message.citations && message.citations.length > 0 && (
                  <div className="flex flex-wrap gap-2 mt-2">
                    {message.citations.map((citation, index) => (
                      <span
                        key={index}
                        className="inline-flex items-center gap-1 px-2 py-1 bg-blue-50 text-blue-700 rounded text-xs border border-blue-200"
                      >
                        [{citation.fileName}, p.{citation.page}]
                      </span>
                    ))}
                  </div>
                )}

                {/* Timestamp and Feedback (AI messages only) */}
                <div className="flex items-center gap-3 mt-2">
                  <span className="text-xs text-gray-500">{message.timestamp}</span>

                  {message.type === 'ai' && (
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => handleFeedback(message.id, 'up')}
                        className={`p-1 rounded transition-colors ${
                          message.feedback === 'up'
                            ? 'bg-green-100 text-green-600'
                            : 'text-gray-400 hover:bg-gray-100 hover:text-green-600'
                        }`}
                        title="Helpful"
                      >
                        <ThumbsUp className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => handleFeedback(message.id, 'down')}
                        className={`p-1 rounded transition-colors ${
                          message.feedback === 'down'
                            ? 'bg-red-100 text-red-600'
                            : 'text-gray-400 hover:bg-gray-100 hover:text-red-600'
                        }`}
                        title="Not helpful"
                      >
                        <ThumbsDown className="w-4 h-4" />
                      </button>
                    </div>
                  )}
                </div>
              </div>
            </div>
          ))}

          {/* Streaming Indicator */}
          {isStreaming && (
            <div className="flex justify-start">
              <div className="max-w-2xl w-full">
                <div className="bg-white border border-gray-200 rounded-lg px-4 py-3">
                  <div className="flex items-center gap-2">
                    <div className="flex gap-1">
                      <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                      <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                      <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
                    </div>
                    <span className="text-xs text-gray-500">AI is typing...</span>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Input Bar */}
      <div className="bg-white border-t border-gray-200 px-4 md:px-6 py-4">
        <div className="max-w-5xl mx-auto flex gap-3">
          <textarea
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            onKeyPress={handleKeyPress}
            placeholder="Type your question here..."
            rows={1}
            className="flex-1 px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent resize-none text-sm"
            disabled={isStreaming}
          />
          <button
            onClick={handleSendMessage}
            disabled={!inputText.trim() || isStreaming}
            className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:bg-gray-300 disabled:cursor-not-allowed flex items-center gap-2"
          >
            <Send className="w-4 h-4" />
            <span className="hidden sm:inline">Send</span>
          </button>
        </div>
      </div>
    </div>
  );
}
